services:
  - type: worker
    name: telegram-bot
    env: python
    pythonVersion: "3.10.12"
    buildCommand: pip install -r requirements.txt
    startCommand: python start_telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DJANGO_API_URL
        value: https://beackkayq.onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: beackkayq.settings 